<a href="https://colab.research.google.com/github/ThienThai261/ML_Lab/blob/main/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TASK 1.1

In [ ]:
def Max(n):
    l = []
    while len(l) <= n:
        a = int(input("enter num"))
        l.append(a)
    return max(l)
Max(int(input("enter")))





enter2
enter num1
enter num3
enter num8


8

In [ ]:
def num(n):
    l = []
    while len(l) < n:
        a = int(input("Enter a number: "))
        l.append(a)

    sorted_list = sorted(l)
    print("Sorted list:", sorted_list)
    return sorted_list
num_elements = int(input("Enter the number of elements: "))
num(num_elements)

Enter the number of elements: 3
Enter a number: 1
Enter a number: 5
Enter a number: 4
Sorted list: [1, 4, 5]


[1, 4, 5]

In [ ]:
def negative(n):
    l = []
    while len(l) <= n:
        a = int(input("enter num"))
        l.append(a)
    x = 0
    y = 0
    for i in l :
      if i>0 :
        x+=1
      else:
        y+=1


In [ ]:
def num(n):
    l = []
    while len(l) <= n:
        a = int(input("enter num"))
        l.append(a)
    return sum(l)
num(int(input("enter sum")))

enter sum32
enter num1
enter num2
enter num3


6

TASK 1.2

In [ ]:
def sumfor(n):
  result =0
  op=1
  for i in range (1,n+1):
    op*=i
    result +=op

  print(result)

sumfor(4)

33


TASK 1.3

In [ ]:
class Account():
    def __init__(self, name, email, country, friends, posts):
        self.__name = name
        self.__email = email
        self.__country = country
        self.__friends = friends
        self.__posts = posts

    def maxPost(self):
        max_post = self.__posts[0]
        for post in self.__posts:
            if post > max_post:
                max_post = post
        return max_pos

    def hadPopularPost(self):
        return any(post.likes >= 10 for post in self.__posts)

    def numPosts(self):
        return len(self.__posts)

    def getCountry(self):
        return self.__country

    def getName(self):
        return self.__name

class Post():
  def __init__(self, content, subject, likes):
    self.__content = content
    self.__subject = subject
    self.__likes = likes




class AccountManager():
  def __init__(self, accounts):
    self.__accounts = accounts

  def groupAccountsByPostLike(self):
        return {
            account.numPosts() >= 10: account for account in self.__accounts
        }
  def filterAccounts(self, country):
        # Filter accounts by country
        filtered_accounts = [account for account in self.__accounts if account.getCountry() == country]

        # Sort filtered accounts by number of posts (descending order), then by name (ascending order)
        sorted_accounts = sorted(filtered_accounts, key=lambda account: (-account.getNumPosts(), account.getName()))

        return sorted_accounts

TASK 2.1


In [ ]:
import numpy as np
def makeArray():
 arr = np.arange(10,25,1)
 print (arr)
 result = np.flip(arr)
 print(result)
makeArray()

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


TASK 2.2

In [ ]:
import numpy as np

def repeat_array(arr, n):
    return np.tile(arr, n)

# Example usage:
arr = np.array([1, 2, 3, 4])
n = 3
result = repeat_array(arr, n)
print(result)


[1 2 3 4 1 2 3 4 1 2 3 4]


TASK 2.3

In [ ]:
import numpy as np

def replace_values(arr, threshold):
    arr[arr < threshold] = threshold
    return arr

# Input array
input_array = np.array([[0.42, 0.48, 0.32],
                        [0.74, 0.58, 0.38],
                        [0.51, 0.34, 0.15]])

print("Original array:")
print(input_array)

# Specified threshold
threshold = 0.5

# Replace values less than the threshold
output_array = replace_values(input_array, threshold)

print("Replace all elements of the original array with", threshold, "for values which are greater than", threshold)
print(output_array)


Original array:
[[0.42 0.48 0.32]
 [0.74 0.58 0.38]
 [0.51 0.34 0.15]]
Replace all elements of the original array with 0.5 for values which are greater than 0.5
[[0.5  0.5  0.5 ]
 [0.74 0.58 0.5 ]
 [0.51 0.5  0.5 ]]
